import { Tool } from "@/lib/types";

const createdAt = "2026-08-18T00:00:00.000Z";

function tool(
  name: string,
  url: string,
  description: string,
  category: Tool["category"],
  subcategory: string,
  type: Tool["type"],
  tags: string[],
): Tool {
  const domain = new URL(url).hostname.replace("www.", "");
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  const favorite = ["Shader Gradient", "Railway", "Animations.dev"].includes(name);
  return {
    id: slug,
    name, slug, url, description, category, subcategory, type, tags,
    favorite,
    favoritedAt: favorite ? createdAt : undefined,
    favicon: `https://www.google.com/s2/favicons?domain=${domain}&sz=128`,
    screenshot: `https://image.thum.io/get/width/1200/crop/800/noanimate/${url}`,
    createdAt, updatedAt: createdAt,
  };
}

export const seedTools: Tool[] = [
  tool("gstack", "https://github.com/garrytan/gstack", "Opinionated developer workflows and agent skills for coding projects.", "Development", "Developer Tools", "GitHub Repository", ["GitHub", "Developer Tools", "AI"]),
  tool("Taste Skill Docs", "https://www.tasteskill.dev/docs", "Documentation for a design-focused skill system for frontend work.", "AI", "AI Skills", "Documentation", ["Design", "Frontend", "Skills"]),
  tool("Taste Skill", "https://github.com/Leonxlnx/taste-skill", "Open-source design skill for producing more polished frontend interfaces.", "AI", "AI Skills", "GitHub Repository", ["GitHub", "Design", "Frontend"]),
  tool("React Three Fiber", "https://github.com/pmndrs/react-three-fiber", "React renderer for Three.js and interactive 3D scenes.", "Development", "3D / Library", "GitHub Repository", ["React", "Three.js", "3D", "Open Source"]),
  tool("Shader Gradient", "https://shadergradient.co/", "Create expressive animated gradients for websites and digital products.", "Design", "Gradient", "Tool", ["Gradient", "Animation", "WebGL"]),
  tool("Type UI Design Skills", "https://www.typeui.sh/design-skills", "Curated visual and product design skills for UI work.", "Design", "Design Skills", "Resource", ["UI", "Design", "Skills"]),
  tool("AnimMasterLib", "https://animmasterlib.dev/", "A library of references and recipes for interface animation.", "Design", "Animation", "Resource", ["Motion", "UI", "Inspiration"]),
  tool("Grok Imagine", "https://grok.com/imagine", "Generate and explore images with Grok's image generation experience.", "AI", "Image Generation", "Tool", ["Image", "Generative AI"]),
  tool("Hermes Agent Skills", "https://hermes-agent.nousresearch.com/docs/skills/", "Documentation for reusable skills used by Hermes agents.", "AI", "AI Agents", "Documentation", ["Agents", "Skills", "Documentation"]),
  tool("Railway", "https://railway.com/", "Deploy applications, databases, and services from a Git repository.", "Development", "Deployment", "SaaS", ["Hosting", "Deployment", "Database"]),
  tool("Twilio", "https://www.twilio.com/en-us", "Communications APIs for SMS, voice, email, and authentication flows.", "Development", "API", "SaaS", ["API", "SMS", "Email"]),
  tool("PostHog", "https://posthog.com/", "Product analytics, session replay, feature flags, and experimentation.", "Development", "Analytics", "SaaS", ["Analytics", "Product", "Open Source"]),
  tool("Sentry", "https://sentry.io/welcome/", "Application monitoring, error tracking, and performance debugging.", "Development", "Monitoring", "SaaS", ["Errors", "Performance", "Monitoring"]),
  tool("Paper MCP", "https://paper.design/docs/mcp#overview", "MCP documentation for connecting design context to AI tools.", "AI", "MCP", "Documentation", ["MCP", "Design", "Documentation"]),
  tool("Animations.dev", "https://animations.dev/", "Practical animation patterns and implementation guidance for the web.", "Design", "Animation", "Resource", ["CSS", "Motion", "Frontend"]),
  tool("Emil Design Engineering", "https://emilkowal.ski/skill", "Design engineering guidance for polished interfaces and motion.", "Design", "Design Skills", "Resource", ["UI", "Animation", "Skills"]),
  tool("Baserow", "https://baserow.io/", "Open-source no-code database and application builder.", "Development", "Database", "SaaS", ["Database", "No Code", "Open Source"]),
  tool("Nextcloud", "https://nextcloud.com/", "Self-hosted collaboration, file storage, and productivity platform.", "Productivity", "Collaboration", "SaaS", ["Self Hosted", "Files", "Open Source"]),
  tool("Dribbble", "https://dribbble.com/", "A large gallery of visual design work and UI inspiration.", "Design", "UI Inspiration", "Website", ["Inspiration", "UI", "Portfolio"]),
  tool("Godly", "https://godly.design/", "Curated references for high-quality web and product design.", "Design", "UI Inspiration", "Resource", ["Inspiration", "Web Design", "UI"]),
  tool("Skiper UI", "https://skiper-ui.com/v1/skiper77", "A collection of polished interface components and design references.", "Design", "UI Components", "Library", ["Components", "UI", "React"]),
  tool("BKLit Gauge Chart", "https://bklit.com/docs/components/gauge-chart", "Documentation for a gauge chart component.", "Development", "Library", "Documentation", ["Chart", "Components", "React"]),
  tool("shadcn/ui", "https://ui.shadcn.com/", "Open-code UI components built with Radix and Tailwind CSS.", "Design", "UI Components", "Library", ["React", "Tailwind", "Components"]),
  tool("Get Design", "https://getdesign.md/", "A directory of useful resources for designers and product builders.", "Design", "UI Inspiration", "Resource", ["Directory", "Design", "Inspiration"]),
  tool("Refero Styles", "https://styles.refero.design/", "Searchable UI styling references from real products.", "Design", "UI Patterns", "Resource", ["UI", "Styles", "Inspiration"]),
  tool("Penpot", "https://penpot.app/", "Open-source collaborative design and prototyping platform.", "Design", "Design Tool", "SaaS", ["Design", "Prototyping", "Open Source"]),
  tool("Sticky UI8", "https://sticky.ui8.dev/", "Design resource and interface inspiration collection.", "Design", "UI Inspiration", "Resource", ["UI", "Inspiration"]),
  tool("GoodUI", "https://goodui.org/", "Evidence-informed UI patterns for improving product conversion.", "Design", "UI Patterns", "Resource", ["UX", "Conversion", "Patterns"]),
  tool("Design Spells", "https://designspells.com/spells/camera-opens-from-the-dynamic-island-in-pico-cam", "A catalog of creative UI interactions and implementation ideas.", "Design", "Animation", "Resource", ["Motion", "Interaction", "Inspiration"]),
  tool("21st.dev", "https://21st.dev/", "A marketplace and discovery platform for reusable React UI components.", "Design", "UI Components", "Library", ["React", "Components", "AI"]),
  tool("Aceternity UI", "https://ui.aceternity.com/components/evervault-card", "Animated React components and visual effects for modern interfaces.", "Design", "UI Components", "Library", ["React", "Animation", "Components"]),
  tool("Better-T-Stack", "https://www.better-t-stack.dev/new", "A project generator for modern full-stack TypeScript applications.", "Development", "Project Starter", "Tool", ["Starter", "TypeScript", "React"]),
  tool("Plunk", "https://www.useplunk.com/", "Developer-friendly transactional email platform.", "Development", "Email", "SaaS", ["Email", "API", "Developer Tools"]),
  tool("skills.sh", "https://www.skills.sh/", "Discover reusable skills for coding agents and developer tools.", "AI", "AI Skills", "Website", ["Agents", "Skills", "Directory"]),
  tool("Name That UI", "https://namethatui.com/", "Identify UI patterns and learn the names behind common interfaces.", "Design", "UI Patterns", "Resource", ["UI", "Patterns", "Learning"]),
  tool("Excalidraw", "https://excalidraw.com/", "A collaborative virtual whiteboard for sketches and diagrams.", "Design", "Drawing", "Tool", ["Drawing", "Wireframe", "Collaboration"]),
  tool("draw.io", "https://draw.io/", "Diagramming tool for flowcharts, systems, and documentation.", "Design", "Wireframe", "Tool", ["Diagram", "Flowchart", "Drawing"]),
  tool("Cal.com", "https://app.cal.com/event-types", "Open scheduling infrastructure for booking meetings and events.", "Business", "Scheduling", "SaaS", ["Calendar", "Scheduling", "Open Source"]),
  tool("OpenSEO", "https://openseo.so/pricing", "SEO tooling and insights for improving website visibility.", "Business", "SEO", "SaaS", ["SEO", "Marketing", "Analytics"]),
  tool("Openwork", "https://openworklabs.com/docs/start-here/get-started", "Documentation for an open-source platform for building work applications.", "Development", "Developer Tools", "Documentation", ["Open Source", "Documentation", "Platform"]),
  tool("VibeUI", "https://vibeui.online/", "Browse UI components and interface inspiration for product teams.", "Design", "UI Components", "Resource", ["UI", "Components", "Inspiration"]),
  tool("Hugging Face Datasets", "https://huggingface.co/datasets?sort=trending", "Discover and browse community datasets for machine learning, including text, image, audio, and video data.", "AI", "AI Tools", "Resource", ["Datasets", "Machine Learning", "Open Source"]),
  tool("Google Flow", "https://labs.google/fx/id/tools/flow", "Google's AI creative studio for generating and editing high-fidelity images, videos, and creative tools.", "AI", "Image Generation", "Tool", ["Video Generation", "Image", "Google AI"]),
  tool("Google Stitch", "https://stitch.withgoogle.com/u/3/?pli=1", "Generate interface designs and frontend code from natural-language prompts.", "Design", "UI Components", "Tool", ["AI", "UI", "Prototyping", "Google"]),
  tool("Google AI Studio", "https://aistudio.google.com/u/3/apps?pli=1&project=gen-lang-client-0617800185", "Prototype, test, and build applications with Google's Gemini models.", "AI", "Coding", "Tool", ["Gemini", "Prototyping", "Developer Tools"]),
  tool("Google Opal", "https://opal.google/landing/", "Build and share small AI-powered applications with natural language and visual workflows.", "AI", "AI Tools", "Tool", ["No Code", "Agents", "Google AI"]),
  tool("NotebookLM", "https://notebook.google.com/notebook/59cba6ff-f4c5-4f33-b265-7b4cf26cd2c8?authuser=3&pli=1", "An AI research assistant that works from the documents and sources you provide.", "AI", "AI Tools", "Tool", ["Research", "Notes", "Google AI"]),
  tool("Google Pomelli", "https://labs.google.com/pomelli/about/", "Google Labs experiment for creating on-brand marketing campaigns with AI.", "AI", "AI Tools", "Tool", ["Marketing", "Brand", "Google AI"]),
  tool("Gemini Canvas", "https://gemini.google.com/u/3/canvas?redirect=home&hl=id-ID&icid=microsite_gemini_canvas_page&pageId=none", "An interactive Gemini workspace for drafting, coding, and refining projects.", "AI", "Coding", "Tool", ["Gemini", "Writing", "Prototyping"]),
  tool("Pocket TTS", "https://github.com/kyutai-labs/pocket-tts", "A lightweight text-to-speech model designed to run efficiently on CPU devices.", "AI", "AI Tools", "GitHub Repository", ["TTS", "Audio", "Open Source"]),
  tool("Instatic", "https://github.com/corebunch/instatic", "Self-hosted visual CMS and website builder that outputs clean static pages.", "Development", "Framework", "GitHub Repository", ["CMS", "Self Hosted", "Static Site"]),
  tool("Text to CAD", "https://github.com/earthtojake/text-to-cad", "A library of agent skills for CAD, CAE, and CAM workflows.", "AI", "AI Skills", "GitHub Repository", ["CAD", "Agents", "Skills"]),
  tool("No AI Slop", "https://github.com/petergyang/no-ai-slop", "A writing skill that removes common AI-generated phrasing patterns from drafts.", "AI", "AI Skills", "GitHub Repository", ["Writing", "Editing", "Skills"]),
  tool("npxskillui", "https://github.com/amaancoderx/npxskillui", "Command-line tool for discovering and installing UI skills for agent-assisted development.", "Development", "Developer Tools", "GitHub Repository", ["CLI", "UI", "AI"]),
  tool("Buzz", "https://github.com/block/buzz", "A communication platform for coordinating a hive of AI agents.", "AI", "AI Agents", "GitHub Repository", ["Agents", "Collaboration", "Open Source"]),
  tool("Meetily", "https://github.com/Zackriya-Solutions/meetily", "Privacy-first local AI meeting assistant with transcription, speaker diarization, and summaries.", "Productivity", "Collaboration", "GitHub Repository", ["Meetings", "Transcription", "Self Hosted"]),
  tool("Hyperframes", "https://github.com/heygen-com/hyperframes", "Render videos from HTML and web content, designed for agent workflows.", "Development", "Library", "GitHub Repository", ["Video", "HTML", "Agents"]),
  tool("Open Generative AI", "https://github.com/Anil-matcha/Open-Generative-AI", "Self-hosted open-source studio for AI image and video generation models.", "AI", "Image Generation", "GitHub Repository", ["Image", "Video Generation", "Self Hosted"]),
  tool("Camofox Browser", "https://github.com/jo-inc/camofox-browser", "Stealth headless browser for AI agents, compatible with Puppeteer and Playwright workflows.", "Development", "Developer Tools", "GitHub Repository", ["Browser Automation", "Playwright", "Agents"]),
  tool("AutoScraper", "https://github.com/alirezamika/autoscraper", "A lightweight Python library that learns and automates web data scraping.", "Development", "Developer Tools", "GitHub Repository", ["Python", "Scraping", "Automation"]),
  tool("Kimi K3 in C", "https://github.com/FareedKhan-dev/kimi-k3-in-c", "Portable C implementation for running Kimi K3 inference on a CPU with minimal dependencies.", "AI", "Coding", "GitHub Repository", ["LLM", "C", "Local AI"]),
  tool("Generative AI for Beginners", "https://github.com/microsoft/generative-ai-for-beginners", "A 21-lesson curriculum for learning how to build with generative AI.", "AI", "AI Skills", "GitHub Repository", ["Learning", "Generative AI", "Microsoft"]),
];
